<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="cuenta_ctacte_histVencido-20240606121412" tests="2" file=".py" time="36.291" timestamp="2024-06-06T12:14:48" failures="0" errors="2" skipped="0">
	<testcase classname="cuenta_ctacte_histVencido" name="test_ctacte_historica" time="0.000" timestamp="0001-01-01T00:00:00" file="CtaCte_HistoVencido.py" line="17">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF77F011F52+60322]
	(No symbol) [0x00007FF77EF8CEC9]
	(No symbol) [0x00007FF77EE47EBA]
	(No symbol) [0x00007FF77EE1D5A5]
	(No symbol) [0x00007FF77EEC36B7]
	(No symbol) [0x00007FF77EEDB331]
	(No symbol) [0x00007FF77EEBBFC3]
	(No symbol) [0x00007FF77EE89617]
	(No symbol) [0x00007FF77EE8A211]
	GetHandleVerifier [0x00007FF77F3294AD+3301629]
	GetHandleVerifier [0x00007FF77F3736D3+3605283]
	GetHandleVerifier [0x00007FF77F369450+3563680]
	GetHandleVerifier [0x00007FF77F0C4326+790390]
	(No symbol) [0x00007FF77EF9750F]
	(No symbol) [0x00007FF77EF93404]
	(No symbol) [0x00007FF77EF93592]
	(No symbol) [0x00007FF77EF82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaCte_HistoVencido.py", line 84, in test_ctacte_historica
    find_and_click_element(self.driver, select_arrow_1, clicks)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 381, in find_and_click_element
    element.click()
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF77F011F52+60322]
	(No symbol) [0x00007FF77EF8CEC9]
	(No symbol) [0x00007FF77EE47EBA]
	(No symbol) [0x00007FF77EE1D5A5]
	(No symbol) [0x00007FF77EEC36B7]
	(No symbol) [0x00007FF77EEDB331]
	(No symbol) [0x00007FF77EEBBFC3]
	(No symbol) [0x00007FF77EE89617]
	(No symbol) [0x00007FF77EE8A211]
	GetHandleVerifier [0x00007FF77F3294AD+3301629]
	GetHandleVerifier [0x00007FF77F3736D3+3605283]
	GetHandleVerifier [0x00007FF77F369450+3563680]
	GetHandleVerifier [0x00007FF77F0C4326+790390]
	(No symbol) [0x00007FF77EF9750F]
	(No symbol) [0x00007FF77EF93404]
	(No symbol) [0x00007FF77EF93592]
	(No symbol) [0x00007FF77EF82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]

]]></error>
	</testcase>
	<testcase classname="cuenta_ctacte_histVencido" name="test_ctacte_historica" time="36.291" timestamp="2024-06-06T12:14:48" file="CtaCte_HistoVencido.py" line="17">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF77F011F52+60322]
	(No symbol) [0x00007FF77EF8CEC9]
	(No symbol) [0x00007FF77EE47EBA]
	(No symbol) [0x00007FF77EE1D5A5]
	(No symbol) [0x00007FF77EEC36B7]
	(No symbol) [0x00007FF77EECA812]
	(No symbol) [0x00007FF77EEBC1E0]
	(No symbol) [0x00007FF77EE89617]
	(No symbol) [0x00007FF77EE8A211]
	GetHandleVerifier [0x00007FF77F3294AD+3301629]
	GetHandleVerifier [0x00007FF77F3736D3+3605283]
	GetHandleVerifier [0x00007FF77F369450+3563680]
	GetHandleVerifier [0x00007FF77F0C4326+790390]
	(No symbol) [0x00007FF77EF9750F]
	(No symbol) [0x00007FF77EF93404]
	(No symbol) [0x00007FF77EF93592]
	(No symbol) [0x00007FF77EF82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaCte_HistoVencido.py", line 194, in tearDown
    self.driver.close()
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 459, in close
    self.execute(Command.CLOSE)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF77F011F52+60322]
	(No symbol) [0x00007FF77EF8CEC9]
	(No symbol) [0x00007FF77EE47EBA]
	(No symbol) [0x00007FF77EE1D5A5]
	(No symbol) [0x00007FF77EEC36B7]
	(No symbol) [0x00007FF77EECA812]
	(No symbol) [0x00007FF77EEBC1E0]
	(No symbol) [0x00007FF77EE89617]
	(No symbol) [0x00007FF77EE8A211]
	GetHandleVerifier [0x00007FF77F3294AD+3301629]
	GetHandleVerifier [0x00007FF77F3736D3+3605283]
	GetHandleVerifier [0x00007FF77F369450+3563680]
	GetHandleVerifier [0x00007FF77F0C4326+790390]
	(No symbol) [0x00007FF77EF9750F]
	(No symbol) [0x00007FF77EF93404]
	(No symbol) [0x00007FF77EF93592]
	(No symbol) [0x00007FF77EF82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]

]]></error>
	</testcase>
</testsuite>
