<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Onboarding_test_tenant-20240612175226" tests="1" file=".py" time="113.225" timestamp="2024-06-12T17:54:19" failures="0" errors="1" skipped="0">
	<testcase classname="Onboarding_test_tenant" name="test_tenat_onboarding" time="113.225" timestamp="2024-06-12T17:54:19" file="Onboarding.py" line="28">
		<error type="InvalidArgumentException" message="Message: invalid argument: File not found : C:/Users/luist/OneDrive/Escritorio/Capturas de pantalla/2022-02-14 (5).png
  (Session info: chrome=125.0.6422.144)
Stacktrace:
	GetHandleVerifier [0x00007FF6D1B11F52+60322]
	(No symbol) [0x00007FF6D1A8CEC9]
	(No symbol) [0x00007FF6D1947EBA]
	(No symbol) [0x00007FF6D199028B]
	(No symbol) [0x00007FF6D19BC21A]
	(No symbol) [0x00007FF6D198ADB6]
	(No symbol) [0x00007FF6D19BC430]
	(No symbol) [0x00007FF6D19DBC80]
	(No symbol) [0x00007FF6D19BBFC3]
	(No symbol) [0x00007FF6D1989617]
	(No symbol) [0x00007FF6D198A211]
	GetHandleVerifier [0x00007FF6D1E294AD+3301629]
	GetHandleVerifier [0x00007FF6D1E736D3+3605283]
	GetHandleVerifier [0x00007FF6D1E69450+3563680]
	GetHandleVerifier [0x00007FF6D1BC4326+790390]
	(No symbol) [0x00007FF6D1A9750F]
	(No symbol) [0x00007FF6D1A93404]
	(No symbol) [0x00007FF6D1A93592]
	(No symbol) [0x00007FF6D1A82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Onboarding.py", line 200, in test_tenat_onboarding
    upload_file_after_click(self.driver, select_field3, element_archive_4, archive3)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 911, in upload_file_after_click
    upload_input_element.send_keys(file_path)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : C:/Users/luist/OneDrive/Escritorio/Capturas de pantalla/2022-02-14 (5).png
  (Session info: chrome=125.0.6422.144)
Stacktrace:
	GetHandleVerifier [0x00007FF6D1B11F52+60322]
	(No symbol) [0x00007FF6D1A8CEC9]
	(No symbol) [0x00007FF6D1947EBA]
	(No symbol) [0x00007FF6D199028B]
	(No symbol) [0x00007FF6D19BC21A]
	(No symbol) [0x00007FF6D198ADB6]
	(No symbol) [0x00007FF6D19BC430]
	(No symbol) [0x00007FF6D19DBC80]
	(No symbol) [0x00007FF6D19BBFC3]
	(No symbol) [0x00007FF6D1989617]
	(No symbol) [0x00007FF6D198A211]
	GetHandleVerifier [0x00007FF6D1E294AD+3301629]
	GetHandleVerifier [0x00007FF6D1E736D3+3605283]
	GetHandleVerifier [0x00007FF6D1E69450+3563680]
	GetHandleVerifier [0x00007FF6D1BC4326+790390]
	(No symbol) [0x00007FF6D1A9750F]
	(No symbol) [0x00007FF6D1A93404]
	(No symbol) [0x00007FF6D1A93592]
	(No symbol) [0x00007FF6D1A82F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]

]]></error>
		<system-out><![CDATA[El texto es visible para el usuario
El texto fue validado correctamente: DOCUMENTACIÓN
El texto es visible para el usuario
El texto fue validado correctamente: Para poder continuar al siguiente paso, será obligatorio completar los campos que se muestran a continuación.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
Error presente. Intentando con otro CUIT.
CUIT válido insertado: 10-96855029-8
Archivo 'C:/Users/luist/OneDrive/Escritorio/Facturas/Contratos-1023-JUAN DEMO.xls' cargado con éxito después de hacer clic en el chevron!
Checkbox con XPAHT '/html/body/app-root/app-layout/app-vertical/div/div/div/div/app-documentation-process/div/div/aw-wizard/div/app-account-type/div/div[3]/app-checks/div/input' seleccionado con éxito!
El texto es visible para el usuario
El texto fue validado correctamente: Estado Impositivo
El texto es visible para el usuario
El texto fue validado correctamente: Apertura de legajo
Archivo 'C:/Users/luist/OneDrive/Escritorio/Facturas/fractura Bezatbeth_files/factura Bezatbeth.pdf' cargado con éxito después de hacer clic en el chevron!
]]></system-out>
	</testcase>
</testsuite>
