<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HomeTenant-20240514151238" tests="1" file=".py" time="64.514" timestamp="2024-05-14T15:13:43" failures="0" errors="1" skipped="0">
	<testcase classname="HomeTenant" name="test_start_tenant" time="64.514" timestamp="2024-05-14T15:13:43" file="Home.py" line="19">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.202)
Stacktrace:
	GetHandleVerifier [0x00007FF6CBA11522+60802]
	(No symbol) [0x00007FF6CB98AC22]
	(No symbol) [0x00007FF6CB847CE4]
	(No symbol) [0x00007FF6CB81DFDF]
	(No symbol) [0x00007FF6CB8C1E57]
	(No symbol) [0x00007FF6CB8D98D1]
	(No symbol) [0x00007FF6CB8BA923]
	(No symbol) [0x00007FF6CB888FEC]
	(No symbol) [0x00007FF6CB889C21]
	GetHandleVerifier [0x00007FF6CBD141BD+3217949]
	GetHandleVerifier [0x00007FF6CBD56157+3488183]
	GetHandleVerifier [0x00007FF6CBD4F0DF+3459391]
	GetHandleVerifier [0x00007FF6CBACB8E6+823622]
	(No symbol) [0x00007FF6CB995FBF]
	(No symbol) [0x00007FF6CB990EE4]
	(No symbol) [0x00007FF6CB991072]
	(No symbol) [0x00007FF6CB9818C4]
	BaseThreadInitThunk [0x00007FFCF149257D+29]
	RtlUserThreadStart [0x00007FFCF2C2AA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Home.py", line 49, in test_start_tenant
    validate_text(self.driver, page_hello, text_expected  )
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 455, in validate_text
    valor = elemento.text
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.202)
Stacktrace:
	GetHandleVerifier [0x00007FF6CBA11522+60802]
	(No symbol) [0x00007FF6CB98AC22]
	(No symbol) [0x00007FF6CB847CE4]
	(No symbol) [0x00007FF6CB81DFDF]
	(No symbol) [0x00007FF6CB8C1E57]
	(No symbol) [0x00007FF6CB8D98D1]
	(No symbol) [0x00007FF6CB8BA923]
	(No symbol) [0x00007FF6CB888FEC]
	(No symbol) [0x00007FF6CB889C21]
	GetHandleVerifier [0x00007FF6CBD141BD+3217949]
	GetHandleVerifier [0x00007FF6CBD56157+3488183]
	GetHandleVerifier [0x00007FF6CBD4F0DF+3459391]
	GetHandleVerifier [0x00007FF6CBACB8E6+823622]
	(No symbol) [0x00007FF6CB995FBF]
	(No symbol) [0x00007FF6CB990EE4]
	(No symbol) [0x00007FF6CB991072]
	(No symbol) [0x00007FF6CB9818C4]
	BaseThreadInitThunk [0x00007FFCF149257D+29]
	RtlUserThreadStart [0x00007FFCF2C2AA48+40]

]]></error>
	</testcase>
</testsuite>
