<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="contrato_tenant-20240405155651" tests="1" file=".py" time="12.695" timestamp="2024-04-05T15:57:04" failures="0" errors="1" skipped="0">
	<testcase classname="contrato_tenant" name="test_contrato_tenant" time="12.695" timestamp="2024-04-05T15:57:04" file="Cuentacontrato.py" line="22">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.105)
Stacktrace:
	GetHandleVerifier [0x00007FF7FCEB7072+63090]
	(No symbol) [0x00007FF7FCE22CC2]
	(No symbol) [0x00007FF7FCCBEC65]
	(No symbol) [0x00007FF7FCC9CA7C]
	(No symbol) [0x00007FF7FCD2D687]
	(No symbol) [0x00007FF7FCD42AC1]
	(No symbol) [0x00007FF7FCD26D83]
	(No symbol) [0x00007FF7FCCF83A8]
	(No symbol) [0x00007FF7FCCF9441]
	GetHandleVerifier [0x00007FF7FD2B25CD+4238285]
	GetHandleVerifier [0x00007FF7FD2EF72D+4488493]
	GetHandleVerifier [0x00007FF7FD2E7A0F+4456463]
	GetHandleVerifier [0x00007FF7FCF905B6+953270]
	(No symbol) [0x00007FF7FCE2E58F]
	(No symbol) [0x00007FF7FCE29264]
	(No symbol) [0x00007FF7FCE2939B]
	(No symbol) [0x00007FF7FCE19BD4]
	BaseThreadInitThunk [0x00007FF89FEF257D+29]
	RtlUserThreadStart [0x00007FF8A17AAA58+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Cuentacontrato.py", line 26, in test_contrato_tenant
    self.login_helper.search_and_select_account("1023")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Loginhelper.py", line 24, in search_and_select_account
    input_element = find_element_by_id(self.driver, "search-options")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\FindElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.105)
Stacktrace:
	GetHandleVerifier [0x00007FF7FCEB7072+63090]
	(No symbol) [0x00007FF7FCE22CC2]
	(No symbol) [0x00007FF7FCCBEC65]
	(No symbol) [0x00007FF7FCC9CA7C]
	(No symbol) [0x00007FF7FCD2D687]
	(No symbol) [0x00007FF7FCD42AC1]
	(No symbol) [0x00007FF7FCD26D83]
	(No symbol) [0x00007FF7FCCF83A8]
	(No symbol) [0x00007FF7FCCF9441]
	GetHandleVerifier [0x00007FF7FD2B25CD+4238285]
	GetHandleVerifier [0x00007FF7FD2EF72D+4488493]
	GetHandleVerifier [0x00007FF7FD2E7A0F+4456463]
	GetHandleVerifier [0x00007FF7FCF905B6+953270]
	(No symbol) [0x00007FF7FCE2E58F]
	(No symbol) [0x00007FF7FCE29264]
	(No symbol) [0x00007FF7FCE2939B]
	(No symbol) [0x00007FF7FCE19BD4]
	BaseThreadInitThunk [0x00007FF89FEF257D+29]
	RtlUserThreadStart [0x00007FF8A17AAA58+40]

]]></error>
	</testcase>
</testsuite>
