<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="detalle_ctro_entregaVentas-20240715153931" tests="1" file=".py" time="59.567" timestamp="2024-07-15T15:40:31" failures="1" errors="0" skipped="0">
	<testcase classname="detalle_ctro_entregaVentas" name="test_detail_deriverySales" time="59.567" timestamp="2024-07-15T15:40:31" file="CtaCtoDtalEntVta.py" line="22">
		<failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaCtoDtalEntVta.py", line 106, in test_detail_deriverySales
    validate_text_visible(self.driver, element1, number_expected)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 1174, in validate_text_visible
    assert text_obtained == text_expected
AssertionError
]]></failure>
		<system-out><![CDATA[¡Elemento encontrado y clickeado 3 veces con éxito!
¡Elemento encontrado y clickeado 5 veces con éxito!
¡Elemento encontrado y clickeado 3 veces con éxito!
El texto encontrado es  Estado De Mis Contratos
El texto es visible para el usuario
]]></system-out>
	</testcase>
</testsuite>
